import { MenuItem, Select } from "@mui/material";

interface DropdownProps {
    language: string;
    setLanguage: any;
}

// Generated by GPT-4o
function Dropdown(props: DropdownProps) {
    // Example options for the dropdown
    const options = [
        'English',
        'Spanish',
        'French',
        'German',
        'Italian',
        'Portuguese',
        'Dutch',
    ];

    const handleChange = (event: any) => {
        props.setLanguage(event.target.value);
    }

    return (
        <Select
            label="Language"
            value={props.language}
            onChange={handleChange}
        >
            {options.map((option, index) => {
                return (
                    <MenuItem key={index} value={option}>{option}</MenuItem>
                );
            })}
        </Select>
    );
}

export default Dropdown;