interface DropdownProps {
    language: string;
    changeLanguage: any;
}

// Generated by GPT-4o
function Dropdown(props: DropdownProps) {
    // Example options for the dropdown
    const options = [
        'English',
        'Spanish',
        'French',
        'German',
        'Italian',
        'Portuguese',
        'Dutch',
    ];

    return (
        <div>
            <select value={props.language} onChange={props.changeLanguage}>
                <option value="">Select an option</option>
                {options.map((option, index) => (
                    <option key={index} value={option}>
                        {option}
                    </option>
                ))}
            </select>
        </div>
    );
}

export default Dropdown;